info:
  name:
    human: 'test_plugin'
    model: 'test_plugin'
  description:
    human: 'Human description of the test plugin.'
    model: 'Model description of the test plugin.'
  logo_url: '/public/logo.png'
  contact_email: '@contact'
  legal_info_url: '/api/plugin/legal'
auth:
  type: 'oauth'
  scope: 'read'
  verification_tokens:
    openai: 'Replace_this_string_with_the_verification_token_generated_in_the_ChatGPT_UI'
